<%@ Page Title="" Language="C#" MasterPageFile="~/Hotel.Master" AutoEventWireup="true" CodeBehind="ManageBooking.aspx.cs" Inherits="HotelBookingSystem.Admin.ManageBooking" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style2 {
            text-align: center;
        }
        .auto-style3 {
            width: 164px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <table style="width: 100%;">
        <tr>
            <td class="auto-style2" colspan="3"><strong>Manage Booking</strong></td>
        </tr>
        <tr>
            <td class="auto-style3">Enter Booking ID:</td>
            <td>
                <asp:TextBox ID="txtBooking" runat="server" OnTextChanged="TextBox1_TextChanged" Width="224px"></asp:TextBox>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server"></asp:SqlDataSource>
                <asp:Button ID="btnSearch" runat="server" OnClick="btnSearch_Click" Text="Search" />
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td class="auto-style3">Table:</td>
            <td>
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="BookingID" DataSourceID="SqlDataSource3" EnableViewState="False" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
                    <Columns>
                        <asp:CommandField ShowSelectButton="True" />
                        <asp:BoundField DataField="BookingID" HeaderText="BookingID" ReadOnly="True" SortExpression="BookingID" />
                        <asp:BoundField DataField="BookingDateAndTime" HeaderText="BookingDateAndTime" SortExpression="BookingDateAndTime" />
                        <asp:BoundField DataField="ReservationDate" HeaderText="ReservationDate" SortExpression="ReservationDate" />
                        <asp:BoundField DataField="ReservationTime" HeaderText="ReservationTime" SortExpression="ReservationTime" />
                        <asp:BoundField DataField="NumOfGuest" HeaderText="NumOfGuest" SortExpression="NumOfGuest" />
                        <asp:BoundField DataField="CustomerID" HeaderText="CustomerID" SortExpression="CustomerID" />
                        <asp:BoundField DataField="RoomID" HeaderText="RoomID" SortExpression="RoomID" />
                        <asp:BoundField DataField="ServicesID" HeaderText="ServicesID" SortExpression="ServicesID" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" ProviderName="<%$ ConnectionStrings:ConnectionString2.ProviderName %>" SelectCommand="SELECT * FROM [Booking]"></asp:SqlDataSource>
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>

</asp:Content>
